"""Change geom to generic Geometry

Revision ID: 589c9940a798
Revises: be0cf5749972
Create Date: 2025-06-17 18:44:46.309956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = '589c9940a798'
down_revision: Union[str, None] = 'be0cf5749972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'geom',
               existing_type=Geometry(geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               type_=Geometry(from_text='ST_GeomFromEWKT', name='geometry'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'geom',
               existing_type=Geometry(from_text='ST_GeomFromEWKT', name='geometry'),
               type_=Geometry(geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               existing_nullable=True)
    # ### end Alembic commands ###
