"""Add itemsv2 table

Revision ID: 889bbde5f833
Revises: 7999867ca4b0
Create Date: 2025-06-23 00:56:01.704924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '889bbde5f833'
down_revision: Union[str, None] = '7999867ca4b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_items_v2_id', table_name='items_v2')
    op.drop_index('ix_items_v2_name', table_name='items_v2')
    op.drop_table('items_v2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items_v2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('geom', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='items_v2_pkey')
    )
    op.create_index('ix_items_v2_name', 'items_v2', ['name'], unique=False)
    op.create_index('ix_items_v2_id', 'items_v2', ['id'], unique=False)
    # ### end Alembic commands ###
