"""Change geom to POLYGON

Revision ID: be0cf5749972
Revises: 95f485ad57fa
Create Date: 2025-06-17 18:36:12.071165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = 'be0cf5749972'
down_revision: Union[str, None] = '95f485ad57fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'geom',
               existing_type=Geometry(geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               type_=Geometry(geometry_type='POLYGON', from_text='ST_GeomFromEWKT', name='geometry'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'geom',
               existing_type=Geometry(geometry_type='POLYGON', from_text='ST_GeomFromEWKT', name='geometry'),
               type_=Geometry(geometry_type='POINT', from_text='ST_GeomFromEWKT', name='geometry', _spatial_index_reflected=True),
               existing_nullable=True)
    # ### end Alembic commands ###
